FROM  python:3
COPY ./chat.html /templates/chat.html
COPY ./recovery.html /templates/recovery.html
COPY ./login.html /templates/login.html
COPY ./register.html /templates/register.html
COPY ./app.py /app.py
COPY ./req.txt /templates/req.txt
RUN pip install -r /templates/req.txt
ENV API-KEY='YOUR-API-KEY'
EXPOSE 3435
ENTRYPOINT [ "python3", "app.py" ]
