FROM  python:3
COPY ./home.html /templates/home.html
COPY ./app.py /app.py
COPY ./req.txt /templates/req.txt
RUN pip install -r /templates/req.txt
ENV API-KEY='YOUR-API-KEY'
EXPOSE 3435
ENTRYPOINT [ "python3", "app.py" ]
